
export const companyInfo = {
  name: "ART PLASTER",
  legal: "ART PLASTER SARL — Capital social : 100.000,00 Dhs",
  director: "MABCHOUR MOHAMED",
  address: process.env.NEXT_PUBLIC_COMPANY_ADDRESS ?? "Avenue Ali Bnou Abi Taleb, Sect C, Imm 15 (GH/5), Magasin N°6, Hay Rahma, Salé, Maroc",
  city: "Salé, Maroc",
  phone: process.env.NEXT_PUBLIC_COMPANY_PHONE ?? "06.62.37.40.34",
  gsm: process.env.NEXT_PUBLIC_COMPANY_GSM ?? "06.64.01.90.87",
  email: process.env.NEXT_PUBLIC_COMPANY_EMAIL ?? "contact@artplaster.ma",
  rc: process.env.NEXT_PUBLIC_COMPANY_RC ?? "",
  cnss: process.env.NEXT_PUBLIC_COMPANY_CNSS ?? "",
  ice: process.env.NEXT_PUBLIC_COMPANY_ICE ?? "",
  hours: "Lun-Ven: 08:30 - 18:30 / Sam: 09:00 - 13:00",
  socials: {
    instagram: "https://instagram.com/artplaster",
    facebook: "https://facebook.com/artplaster",
    linkedin: "https://linkedin.com/company/artplaster",
    youtube: "https://youtube.com/artplaster",
  },
};

export const marqueeItems = [
  "Travaux de Plâtre",
  "Faux Plafonds",
  "Plafonds Décoratifs",
  "Hôtellerie de Luxe",
  "Rénovation Patrimoine",
  "Secteur Bancaire",
  "Projets de Santé",
  "Éducation & Culture",
  "Espaces Commerciaux",
  "Finitions Premium",
  "Construction Neuve",
  "Leader National",
];

export const stats = [
  { value: 300, suffix: "+", label: "Projets Livrés", icon: "Briefcase" },
  { value: 45, suffix: "", label: "Artisans & Techniciens", icon: "Users" },
  { value: 6, suffix: "", label: "Secteurs d'Activité", icon: "Building2" },
  { value: 15, suffix: "+", label: "Années d'Expertise", icon: "Award" },
];

export const categories = [
  "Tous",
  "Hôtellerie",
  "Santé",
  "Office",
  "Éducation",
  "Commercial",
  "Résidentiel",
];

export const projects = [
  // ═══ HÔTELLERIE ═══
  {
    id: "barcelo-tanger",
    slug: "barcelo-tanger",
    title: "Hôtel Barceló 5*",
    category: "Hôtellerie",
    location: "Tanger",
    image: "/images/projects/Hotellerie__hotel_barcelo_tanger__001.jpg",
    gallery: [
      "/images/projects/Hotellerie__hotel_barcelo_tanger__001.jpg",
      "/images/projects/Hotellerie__hotel_barcelo_tanger__002.jpg",
      "/images/projects/Hotellerie__hotel_barcelo_tanger__003.jpg",
      "/images/projects/Hotellerie__hotel_barcelo_tanger__004.jpg",
    ],
    surface: "22 000 m²",
    duration: "12 mois",
    year: "2021",
    client: "Barceló Hotels & Resorts",
    description: "Aménagement complet des parties communes, du lobby et des suites. Réalisation de plafonds décoratifs en staff, corniches lumineuses, et enduits décoratifs haut de gamme pour refléter le standing 5 étoiles de l'établissement.",
    tags: ["Staff Décoratif", "Corniches Lumineuses", "Enduits Fins", "Suites de Luxe"],
    featured: true,
  },
  {
    id: "hotel-marriott-rabat",
    slug: "hotel-marriott-rabat",
    title: "Hôtel Marriott — Sheraton Casablanca",
    category: "Hôtellerie",
    location: "Casablanca",
    image: "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__001.jpg",
    gallery: [
      "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__001.jpg",
      "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__002.jpg",
      "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__003.jpg",
      "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__004.jpg",
      "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__005.jpg",
      "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__006.jpg",
    ],
    surface: "24 000 m²",
    duration: "15 mois",
    year: "2022",
    client: "Marriott International",
    description: "Exécution des travaux de plâtre décoratif, plafonds à caissons dans le centre de conférences, et finitions ultra-lisses pour les revêtements muraux de luxe dans les chambres.",
    tags: ["Plafonds à Caissons", "Finition Luxe", "Salles de Conférence"],
    featured: true,
  },
  {
    id: "hotel-ibis-rabat",
    slug: "hotel-ibis-rabat",
    title: "Hôtel Ibis Rabat Agdal",
    category: "Hôtellerie",
    location: "Rabat",
    image: "/images/projects/Hotellerie__hotel_ibis_rabat_agdal__001.jpg",
    gallery: [
      "/images/projects/Hotellerie__hotel_ibis_rabat_agdal__001.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2023",
    client: "Accor Hotels",
    description: "Travaux complets de plâtrerie et faux plafonds pour l'Hôtel Ibis Rabat Agdal. Réalisation des cloisons, enduits et finitions dans l'ensemble des espaces.",
    tags: ["Hôtellerie", "Faux plafonds", "Plâtrerie"],
    featured: false,
  },
  {
    id: "hotel-ibis-agadir",
    slug: "hotel-ibis-agadir",
    title: "Hôtel Ibis Agadir",
    category: "Hôtellerie",
    location: "Agadir",
    image: "/images/projects/Hotellerie__hotel_ibis_agadir__001.jpg",
    gallery: [
      "/images/projects/Hotellerie__hotel_ibis_agadir__001.jpg",
      "/images/projects/Hotellerie__hotel_ibis_agadir__002.jpg",
      "/images/projects/Hotellerie__hotel_ibis_agadir__003.jpg",
      "/images/projects/Hotellerie__hotel_ibis_agadir__004.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2023",
    client: "Accor Hotels",
    description: "Réalisation des travaux de plâtre pour l'Hôtel Ibis Agadir. Plafonds, cloisons et enduits dans tous les espaces de l'établissement.",
    tags: ["Hôtellerie", "Plâtrerie", "Enduits"],
    featured: false,
  },

  // ═══ SANTÉ ═══
  {
    id: "idfs-marrakech",
    slug: "idfs-marrakech",
    title: "IDFS — Institut de Formation",
    category: "Santé",
    location: "Marrakech",
    image: "/images/projects/Sante__idfs_marrakech__001.jpg",
    gallery: [
      "/images/projects/Sante__idfs_marrakech__001.jpg",
      "/images/projects/Sante__idfs_marrakech__002.jpg",
      "/images/projects/Sante__idfs_marrakech__003.jpg",
    ],
    surface: "6 000 m²",
    duration: "8 mois",
    year: "2019",
    client: "OFPPT",
    description: "Création d'espaces d'apprentissage fonctionnels avec cloisonnement phonique entre les ateliers et les salles de cours. Traitement des plafonds avec dalles acoustiques lumineuses.",
    tags: ["Ateliers Formation", "Isolation Acoustique", "Plafonds Pratiques"],
    featured: false,
  },
  {
    id: "idfs-casablanca",
    slug: "idfs-casablanca",
    title: "IDFS Casablanca",
    category: "Santé",
    location: "Casablanca",
    image: "/images/projects/Sante__idfs_casablanca__001.jpg",
    gallery: [
      "/images/projects/Sante__idfs_casablanca__001.jpg",
      "/images/projects/Sante__idfs_casablanca__002.jpg",
      "/images/projects/Sante__idfs_casablanca__003.jpg",
      "/images/projects/Sante__idfs_casablanca__004.jpg",
      "/images/projects/Sante__idfs_casablanca__005.jpg",
      "/images/projects/Sante__idfs_casablanca__006.jpg",
      "/images/projects/Sante__idfs_casablanca__007.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "IDFS",
    description: "Réalisation complète des travaux de plâtrerie pour établissement médical à Casablanca. Plafonds techniques, cloisons et enduits haute performance.",
    tags: ["Santé", "Plâtrerie technique"],
    featured: true,
  },
  {
    id: "hopital-el-jadida",
    slug: "hopital-el-jadida",
    title: "Hôpital Privé El Jadida",
    category: "Santé",
    location: "El Jadida",
    image: "/images/projects/Sante__hopital_prive_el_jadida__001.jpg",
    gallery: [
      "/images/projects/Sante__hopital_prive_el_jadida__001.jpg",
      "/images/projects/Sante__hopital_prive_el_jadida__002.jpg",
      "/images/projects/Sante__hopital_prive_el_jadida__003.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Groupe Santé Privé",
    description: "Réalisation des travaux de plâtrerie et faux plafonds pour cet établissement de santé. Finitions spéciales pour environnement médical : étanchéité, isolation acoustique et thermique.",
    tags: ["Santé", "Faux plafonds", "Isolation"],
    featured: false,
  },
  {
    id: "fondation-lalla-salma",
    slug: "fondation-lalla-salma",
    title: "Fondation Lalla Salma — CHOP Fès",
    category: "Santé",
    location: "Fès",
    image: "/images/projects/Sante__fondation_lalla_salma_fes__001.jpg",
    gallery: [
      "/images/projects/Sante__fondation_lalla_salma_fes__001.jpg",
      "/images/projects/Sante__fondation_lalla_salma_fes__002.jpg",
      "/images/projects/Sante__fondation_lalla_salma_fes__003.jpg",
      "/images/projects/Sante__fondation_lalla_salma_fes__004.jpg",
    ],
    surface: "12 500 m²",
    duration: "11 mois",
    year: "2017",
    client: "Fondation Lalla Salma",
    description: "Travaux de plâtrerie pour le Centre d'Hématologie et d'Oncologie Pédiatrique de Fès. Plafonds techniques, cloisons et finitions dans les services médicaux.",
    tags: ["Fondation Royale", "Plâtrerie technique", "CHOP"],
    featured: true,
  },
  {
    id: "centre-oncologie-laayoune",
    slug: "centre-oncologie-laayoune",
    title: "Centre Régional d'Oncologie de Laâyoune",
    category: "Santé",
    location: "Laâyoune",
    image: "/images/projects/Sante__centre_oncologie_laayoune__001.jpg",
    gallery: [
      "/images/projects/Sante__centre_oncologie_laayoune__001.jpg",
      "/images/projects/Sante__centre_oncologie_laayoune__002.jpg",
      "/images/projects/Sante__centre_oncologie_laayoune__003.jpg",
      "/images/projects/Sante__centre_oncologie_laayoune__004.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2021",
    client: "Ministère de la Santé",
    description: "Réalisation des plafonds et finitions plâtre pour le Centre Régional d'Oncologie de Laâyoune.",
    tags: ["Santé", "Secteur public"],
    featured: false,
  },
  {
    id: "clinique-anti-age",
    slug: "clinique-anti-age",
    title: "Clinique Anti-Âge",
    category: "Santé",
    location: "Maroc",
    image: "/images/projects/Sante__clinique_anti_age__001.jpg",
    gallery: [
      "/images/projects/Sante__clinique_anti_age__001.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2023",
    client: "Clinique Privée",
    description: "Finitions haut de gamme pour clinique esthétique. Plafonds design et enduits de finition premium.",
    tags: ["Santé", "Luxe", "Finitions premium"],
    featured: false,
  },

  // ═══ OFFICE / BANQUES ═══
  {
    id: "sgmb-siege",
    slug: "sgmb-siege",
    title: "Société Générale — Siège Social",
    category: "Office",
    location: "Rabat",
    image: "/images/projects/Office__societe_generale_siege_social__001.jpg",
    gallery: [
      "/images/projects/Office__societe_generale_siege_social__001.jpg",
      "/images/projects/Office__societe_generale_siege_social__002.jpg",
      "/images/projects/Office__societe_generale_siege_social__003.jpg",
      "/images/projects/Office__societe_generale_siege_social__004.jpg",
      "/images/projects/Office__societe_generale_siege_social__005.jpg",
      "/images/projects/Office__societe_generale_siege_social__006.jpg",
    ],
    surface: "7 000 m²",
    duration: "7 mois",
    year: "2019",
    client: "Société Générale Maroc",
    description: "Aménagement d'une agence flagship et des bureaux régionaux. Finitions murales décoratives à l'accueil et plafonds techniques premium.",
    tags: ["Agence Bancaire", "Prestige", "Siège Social"],
    featured: true,
  },
  {
    id: "agence-agadir-hassan-ii",
    slug: "agence-agadir-hassan-ii",
    title: "Agence Agadir Hassan II",
    category: "Office",
    location: "Agadir",
    image: "/images/projects/Office__agence_agadir_hassan_ii__001.jpg",
    gallery: [
      "/images/projects/Office__agence_agadir_hassan_ii__001.jpg",
      "/images/projects/Office__agence_agadir_hassan_ii__002.jpg",
      "/images/projects/Office__agence_agadir_hassan_ii__003.jpg",
      "/images/projects/Office__agence_agadir_hassan_ii__004.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2023",
    client: "Banque Marocaine",
    description: "Réalisation des finitions plâtre pour agence bancaire à Agadir. Plafonds, cloisons et enduits selon les standards premium du secteur financier.",
    tags: ["Agence Bancaire", "Finitions"],
    featured: false,
  },
  {
    id: "agence-el-jadida",
    slug: "agence-el-jadida",
    title: "Agence El Jadida",
    category: "Office",
    location: "El Jadida",
    image: "/images/projects/Office__agence_el_jadida__001.jpg",
    gallery: [
      "/images/projects/Office__agence_el_jadida__001.jpg",
      "/images/projects/Office__agence_el_jadida__002.jpg",
      "/images/projects/Office__agence_el_jadida__003.jpg",
      "/images/projects/Office__agence_el_jadida__004.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2023",
    client: "Banque Marocaine",
    description: "Travaux de plâtrerie complète pour agence bancaire à El Jadida. Faux plafonds, cloisons légères et enduits de finition.",
    tags: ["Agence Bancaire"],
    featured: false,
  },
  {
    id: "agence-meknes",
    slug: "agence-meknes",
    title: "Agence Meknès Baladiya",
    category: "Office",
    location: "Meknès",
    image: "/images/projects/Office__agence_meknes_baladiya__001.jpg",
    gallery: [
      "/images/projects/Office__agence_meknes_baladiya__001.jpg",
      "/images/projects/Office__agence_meknes_baladiya__002.jpg",
      "/images/projects/Office__agence_meknes_baladiya__003.jpg",
      "/images/projects/Office__agence_meknes_baladiya__004.jpg",
      "/images/projects/Office__agence_meknes_baladiya__005.jpg",
      "/images/projects/Office__agence_meknes_baladiya__006.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Banque Marocaine",
    description: "Réalisation des faux plafonds et cloisons pour agence bancaire à Meknès.",
    tags: ["Agence Bancaire", "Faux plafonds"],
    featured: false,
  },
  {
    id: "agence-ouarzazate",
    slug: "agence-ouarzazate",
    title: "Agence Ouarzazate",
    category: "Office",
    location: "Ouarzazate",
    image: "/images/projects/Office__agence_ouarzazate__001.jpg",
    gallery: [
      "/images/projects/Office__agence_ouarzazate__001.jpg",
      "/images/projects/Office__agence_ouarzazate__002.jpg",
      "/images/projects/Office__agence_ouarzazate__003.jpg",
      "/images/projects/Office__agence_ouarzazate__004.jpg",
      "/images/projects/Office__agence_ouarzazate__005.jpg",
      "/images/projects/Office__agence_ouarzazate__006.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Banque Marocaine",
    description: "Travaux de plâtrerie et faux plafonds pour agence bancaire à Ouarzazate.",
    tags: ["Agence Bancaire"],
    featured: false,
  },
  {
    id: "agence-sale",
    slug: "agence-sale",
    title: "Agence Salé El Jadida",
    category: "Office",
    location: "Salé",
    image: "/images/projects/Office__agence_sale_el_jadida__001.jpg",
    gallery: [
      "/images/projects/Office__agence_sale_el_jadida__001.jpg",
      "/images/projects/Office__agence_sale_el_jadida__002.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Banque Marocaine",
    description: "Travaux de finitions plâtre pour agence bancaire à Salé.",
    tags: ["Agence Bancaire"],
    featured: false,
  },
  {
    id: "agence-souk-agadir",
    slug: "agence-souk-agadir",
    title: "Agence Souk Agadir",
    category: "Office",
    location: "Agadir",
    image: "/images/projects/Office__agence_souk_agadir__001.jpg",
    gallery: [
      "/images/projects/Office__agence_souk_agadir__001.jpg",
      "/images/projects/Office__agence_souk_agadir__002.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Banque Marocaine",
    description: "Réalisation des travaux de plâtre pour agence bancaire au Souk d'Agadir.",
    tags: ["Agence Bancaire"],
    featured: false,
  },
  {
    id: "cat-assurance",
    slug: "cat-assurance",
    title: "CAT — Compagnie d'Assurance Transport",
    category: "Office",
    location: "Maroc",
    image: "/images/projects/Office__cat_assurance_transport__001.jpg",
    gallery: [
      "/images/projects/Office__cat_assurance_transport__001.jpg",
      "/images/projects/Office__cat_assurance_transport__002.jpg",
      "/images/projects/Office__cat_assurance_transport__003.jpg",
      "/images/projects/Office__cat_assurance_transport__004.jpg",
      "/images/projects/Office__cat_assurance_transport__005.jpg",
      "/images/projects/Office__cat_assurance_transport__006.jpg",
      "/images/projects/Office__cat_assurance_transport__007.jpg",
      "/images/projects/Office__cat_assurance_transport__008.jpg",
      "/images/projects/Office__cat_assurance_transport__009.jpg",
      "/images/projects/Office__cat_assurance_transport__010.jpg",
      "/images/projects/Office__cat_assurance_transport__011.jpg",
      "/images/projects/Office__cat_assurance_transport__012.jpg",
      "/images/projects/Office__cat_assurance_transport__013.jpg",
      "/images/projects/Office__cat_assurance_transport__014.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "CAT Assurance",
    description: "Réalisation des travaux de plâtre pour les locaux de la Compagnie d'Assurance Transport. Faux plafonds, cloisons et enduits dans les espaces de bureaux.",
    tags: ["Office", "Assurance", "Bureaux"],
    featured: false,
  },

  // ═══ ÉDUCATION / CULTURE ═══
  {
    id: "fondation-med-vi",
    slug: "fondation-med-vi",
    title: "Fondation Mohammed VI Rabat",
    category: "Éducation",
    location: "Rabat",
    image: "/images/projects/Education__fondation_mohamed_vi_rabat__001.jpg",
    gallery: [
      "/images/projects/Education__fondation_mohamed_vi_rabat__001.jpg",
      "/images/projects/Education__fondation_mohamed_vi_rabat__002.jpg",
      "/images/projects/Education__fondation_mohamed_vi_rabat__003.jpg",
      "/images/projects/Education__fondation_mohamed_vi_rabat__004.jpg",
      "/images/projects/Education__fondation_mohamed_vi_rabat__005.jpg",
      "/images/projects/Education__fondation_mohamed_vi_rabat__006.jpg",
    ],
    surface: "15 000 m²",
    duration: "13 mois",
    year: "2021",
    client: "Fondation Mohammed VI",
    description: "Travaux de plâtrerie pour la Fondation Mohammed VI. Plafonds ornementaux, finitions décoratives et enduits de prestige dans ce bâtiment institutionnel de référence nationale.",
    tags: ["Fondation Royale", "Prestige", "Institutionnel"],
    featured: true,
  },
  {
    id: "musee-art",
    slug: "musee-art",
    title: "Musée Mohammed VI des Arts Contemporains",
    category: "Éducation",
    location: "Rabat",
    image: "/images/projects/Education__musee_mohammed_vi__001.jpg",
    gallery: [
      "/images/projects/Education__musee_mohammed_vi__001.jpg",
      "/images/projects/Education__musee_mohammed_vi__002.jpg",
      "/images/projects/Education__musee_mohammed_vi__003.jpg",
      "/images/projects/Education__musee_mohammed_vi__004.jpg",
      "/images/projects/Education__musee_mohammed_vi__005.jpg",
      "/images/projects/Education__musee_mohammed_vi__006.jpg",
      "/images/projects/Education__musee_mohammed_vi__007.jpg",
      "/images/projects/Education__musee_mohammed_vi__008.jpg",
      "/images/projects/Education__musee_mohammed_vi__009.jpg",
      "/images/projects/Education__musee_mohammed_vi__010.jpg",
      "/images/projects/Education__musee_mohammed_vi__011.jpg",
      "/images/projects/Education__musee_mohammed_vi__012.jpg",
      "/images/projects/Education__musee_mohammed_vi__013.jpg",
      "/images/projects/Education__musee_mohammed_vi__014.jpg",
      "/images/projects/Education__musee_mohammed_vi__015.jpg",
      "/images/projects/Education__musee_mohammed_vi__016.jpg",
      "/images/projects/Education__musee_mohammed_vi__017.jpg",
      "/images/projects/Education__musee_mohammed_vi__018.jpg",
      "/images/projects/Education__musee_mohammed_vi__019.jpg",
      "/images/projects/Education__musee_mohammed_vi__020.jpg",
      "/images/projects/Education__musee_mohammed_vi__021.jpg",
      "/images/projects/Education__musee_mohammed_vi__022.jpg",
      "/images/projects/Education__musee_mohammed_vi__023.jpg",
      "/images/projects/Education__musee_mohammed_vi__024.jpg",
      "/images/projects/Education__musee_mohammed_vi__025.jpg",
      "/images/projects/Education__musee_mohammed_vi__026.jpg",
      "/images/projects/Education__musee_mohammed_vi__027.jpg",
      "/images/projects/Education__musee_mohammed_vi__028.jpg",
      "/images/projects/Education__musee_mohammed_vi__029.jpg",
      "/images/projects/Education__musee_mohammed_vi__030.jpg",
      "/images/projects/Education__musee_mohammed_vi__031.jpg",
      "/images/projects/Education__musee_mohammed_vi__032.jpg",
      "/images/projects/Education__musee_mohammed_vi__033.jpg",
    ],
    surface: "5 500 m²",
    duration: "8 mois",
    year: "2021",
    client: "Fondation Nationale des Musées",
    description: "Réalisation des finitions plâtre pour ce musée de référence nationale. Plafonds techniques muséographiques, cloisons et enduits adaptés aux exigences de conservation.",
    tags: ["Culture", "Musée", "Plâtrerie technique"],
    featured: true,
  },

  // ═══ COMMERCIAL ═══
  {
    id: "renault-showroom",
    slug: "renault-showroom",
    title: "Showroom Renault Maroc",
    category: "Commercial",
    location: "Casablanca",
    image: "/images/projects/Commercial__renault_maroc__001.jpg",
    gallery: [
      "/images/projects/Commercial__renault_maroc__001.jpg",
    ],
    surface: "3 000 m²",
    duration: "4 mois",
    year: "2020",
    client: "Renault Maroc",
    description: "Habillage de l'espace d'exposition avec de grands plafonds et des retombées en plaque de plâtre créant des zones de lumière ciblées sur les véhicules.",
    tags: ["Showroom", "Commercial", "Automobile"],
    featured: false,
  },
  {
    id: "showroom-audi",
    slug: "showroom-audi",
    title: "Showroom Audi",
    category: "Commercial",
    location: "Maroc",
    image: "/images/projects/Commercial__showroom_audi__001.jpg",
    gallery: [
      "/images/projects/Commercial__showroom_audi__001.jpg",
      "/images/projects/Commercial__showroom_audi__002.jpg",
      "/images/projects/Commercial__showroom_audi__003.jpg",
      "/images/projects/Commercial__showroom_audi__004.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2023",
    client: "Audi Maroc",
    description: "Finitions haut de gamme pour showroom Audi. Plafonds design et enduits de finition luxe conformes à l'identité premium de la marque.",
    tags: ["Showroom", "Luxe", "Automobile"],
    featured: false,
  },
  {
    id: "boutique-marionnaud",
    slug: "boutique-marionnaud",
    title: "Boutique Marionnaud",
    category: "Commercial",
    location: "Maroc",
    image: "/images/projects/Commercial__boutique_marionnaud__001.jpg",
    gallery: [
      "/images/projects/Commercial__boutique_marionnaud__001.jpg",
      "/images/projects/Commercial__boutique_marionnaud__002.jpg",
      "/images/projects/Commercial__boutique_marionnaud__003.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Marionnaud",
    description: "Finitions plâtre pour boutique Marionnaud. Plafonds design et enduits de finition adaptés à l'univers cosmétique luxe.",
    tags: ["Retail", "Luxe", "Commercial"],
    featured: false,
  },

  // ═══ RÉSIDENTIEL ═══
  {
    id: "villas-californie",
    slug: "villas-californie",
    title: "Projets Résidentiels de Prestige",
    category: "Résidentiel",
    location: "Maroc",
    image: "/images/projects/Residentiel__residentiel_divers__001.jpg",
    gallery: [
      "/images/projects/Residentiel__residentiel_divers__001.jpg",
      "/images/projects/Residentiel__residentiel_divers__002.jpg",
      "/images/projects/Residentiel__residentiel_divers__003.jpg",
      "/images/projects/Residentiel__residentiel_divers__004.jpg",
      "/images/projects/Residentiel__residentiel_divers__005.jpg",
      "/images/projects/Residentiel__residentiel_divers__006.jpg",
      "/images/projects/Residentiel__residentiel_divers__010.jpg",
      "/images/projects/Residentiel__residentiel_divers__015.jpg",
      "/images/projects/Residentiel__residentiel_divers__020.jpg",
      "/images/projects/Residentiel__residentiel_divers__025.jpg",
    ],
    surface: "Variable",
    duration: "Variable",
    year: "2023",
    client: "Clients Privés",
    description: "ART PLASTER réalise des travaux de plâtrerie de haute qualité pour villas et résidences de prestige. Plafonds décoratifs, corniches, rosaces et enduits sur-mesure.",
    tags: ["Résidentiel", "Villa", "Prestige", "Sur-mesure"],
    featured: false,
  },
  {
    id: "reception-riche-bois",
    slug: "reception-riche-bois",
    title: "Réception Société Riche Bois",
    category: "Résidentiel",
    location: "Maroc",
    image: "/images/projects/Residentiel__reception_societe_riche_bois__001.jpg",
    gallery: [
      "/images/projects/Residentiel__reception_societe_riche_bois__001.jpg",
      "/images/projects/Residentiel__reception_societe_riche_bois__002.jpg",
      "/images/projects/Residentiel__reception_societe_riche_bois__003.jpg",
      "/images/projects/Residentiel__reception_societe_riche_bois__004.jpg",
      "/images/projects/Residentiel__reception_societe_riche_bois__005.jpg",
    ],
    surface: "À définir",
    duration: "À définir",
    year: "2022",
    client: "Société Riche Bois",
    description: "Réalisation des travaux de plâtrerie et finitions décoratives pour l'espace de réception. Plafonds ornementaux, corniches et enduits de prestige.",
    tags: ["Réception", "Décoration", "Prestige"],
    featured: false,
  },
];

export const services = [
  {
    id: "plafonds",
    title: "Plafonds Ornementaux",
    subtitle: "Staff décoratif, Corniches, Rosaces",
    description: "Le chef-d'œuvre de tout espace prestigieux. Nous concevons et réalisons des plafonds suspendus en staff avec des motifs traditionnels marocains ou des lignes épurées contemporaines.",
    category: "Architecture",
    icon: "Crown",
    features: ["Coupoles sculptées", "Corniches lumineuses", "Rosaces centrales", "Plafonds à caissons"],
    image: "/images/projects/Hotellerie__hotel_barcelo_tanger__001.jpg",
  },
  {
    id: "faux-plafonds",
    title: "Faux Plafonds Techniques",
    subtitle: "Acoustique, Hygiène, Coupe-feu",
    description: "Solutions techniques complètes pour hôpitaux, bureaux et hôtels. Dalles acoustiques, hygiéniques et coupe-feu conformes aux normes internationales les plus exigeantes.",
    category: "Technique",
    icon: "Layers",
    features: ["Dalles acoustiques", "Plafonds hygiène", "Coupe-feu CF2h", "Plafonds démontables"],
    image: "/images/projects/Sante__idfs_casablanca__001.jpg",
  },
  {
    id: "cloisons",
    title: "Cloisons & Séparations",
    subtitle: "Légères, Coupe-feu, Phoniques",
    description: "Du cloisonnement standard au mur coupe-feu certifié, en passant par les cloisons phoniques pour salles de conférence et hôpitaux. Maîtrise totale des techniques.",
    category: "Construction",
    icon: "Building2",
    features: ["Cloisons légères", "Coupe-feu 2h/4h", "Isolation phonique", "Cloisons vitrées"],
    image: "/images/projects/Office__societe_generale_siege_social__001.jpg",
  },
  {
    id: "hotellerie",
    title: "Agencement Hôtelier",
    subtitle: "Suites, Lobbys, Spas",
    description: "Experts en projets hôteliers depuis plus de 15 ans. ART PLASTER répond aux normes d'exigence des établissements 5 étoiles avec une signature visuelle unique.",
    category: "Grands Projets",
    icon: "Hotel",
    features: ["Cloisons grande hauteur", "Plafonds acoustiques", "Aménagement Spa", "Chambres témoins"],
    image: "/images/projects/Hotellerie__hotel_marriott_casa_sheraton__001.jpg",
  },
  {
    id: "commercial",
    title: "Espaces Commerciaux & Sièges",
    subtitle: "Bureaux, Boutiques, Showrooms",
    description: "Des espaces professionnels qui reflètent l'image de votre marque. Agencements sur-mesure pour banques, institutions publiques et boutiques de luxe.",
    category: "Tertiaire",
    icon: "Store",
    features: ["Agences bancaires", "Intégration domotique", "Plafonds démontables", "Showrooms luxe"],
    image: "/images/projects/Office__cat_assurance_transport__001.jpg",
  },
  {
    id: "residentiel",
    title: "Résidences Privées Haut-Standing",
    subtitle: "Villas & Appartements de Luxe",
    description: "L'excellence à l'échelle intime. Finitions millimétriques pour villas et appartements de prestige. Chaque détail est traité avec la même rigueur que nos grands chantiers.",
    category: "Résidentiel",
    icon: "Home",
    features: ["Lissage extrême", "Habillage cheminées", "Gorges lumineuses", "Staff sur-mesure"],
    image: "/images/projects/Residentiel__residentiel_divers__001.jpg",
  },
];

export const processSteps = [
  {
    number: "01",
    title: "Étude technique",
    description: "Analyse des plans architecturaux, relevé laser sur site et proposition de solutions techniques optimales (acoustique, feu, design).",
    icon: "FileSearch",
  },
  {
    number: "02",
    title: "Prototypage & Moules",
    description: "Création des éléments sur-mesure dans nos ateliers de Salé par nos modeleurs. Validation des échantillons avec les architectes.",
    icon: "Palette",
  },
  {
    number: "03",
    title: "Déploiement Chantier",
    description: "Intervention de nos chefs d'équipe avec un suivi quotidien. Respect rigoureux des plannings et de la co-activité sur chantier.",
    icon: "HardHat",
  },
  {
    number: "04",
    title: "Livraison",
    description: "Réception contradictoire, levée des réserves et garantie sur toutes nos réalisations. Satisfaction client garantie à 100%.",
    icon: "CheckCircle2",
  },
];

export const partners = [
  { name: "Société Générale", slug: "societe-generale" },
  { name: "Accor Hotels", slug: "accor" },
  { name: "Barceló Hotels", slug: "barcelo" },
  { name: "Marriott Sheraton", slug: "marriott" },
  { name: "Fondation Lalla Salma", slug: "fondation-lalla-salma" },
  { name: "Fondation Mohamed VI", slug: "fondation-med-vi" },
  { name: "Renault Maroc", slug: "renault" },
  { name: "Audi Maroc", slug: "audi" },
];

export const testimonials = [
  {
    id: "1",
    quote: "ART PLASTER a réalisé les travaux de plâtrerie de notre hôtel avec une qualité et un professionnalisme remarquables. Leur équipe maîtrise parfaitement les exigences des projets hôteliers de luxe.",
    author: "Direction Technique",
    role: "Barceló Tanger",
    company: "Barceló Hotels & Resorts",
    rating: 5,
    avatar: "/images/projects/Hotellerie__hotel_barcelo_tanger__001.jpg",
  },
  {
    id: "2",
    quote: "Partenaire fiable sur plusieurs de nos agences au Maroc. ART PLASTER respecte les délais, les budgets et livre des travaux de qualité irréprochable.",
    author: "Service Immobilier",
    role: "Société Générale Maroc",
    company: "Société Générale",
    rating: 5,
    avatar: "/images/projects/Office__societe_generale_siege_social__001.jpg",
  },
  {
    id: "3",
    quote: "Les équipes d'ART PLASTER ont parfaitement maîtrisé les contraintes techniques des espaces médicaux. Un savoir-faire reconnu dans notre secteur.",
    author: "Direction des Travaux",
    role: "IDFS Marrakech",
    company: "IDFS",
    rating: 5,
    avatar: "/images/projects/Sante__idfs_marrakech__001.jpg",
  },
];

export const team = [
  {
    name: "MABCHOUR MOHAMED",
    role: "Président & Directeur Général",
    bio: "Fondateur d'ART PLASTER, Mr MABCHOUR MOHAMED dirige l'entreprise avec une vision claire : faire d'ART PLASTER le leader national incontesté des travaux de plâtre au Maroc.",
    image: "/images/projects/Divers__projets_divers_1__001.jpg",
  },
  {
    name: "Direction Technique",
    role: "Directeur Technique",
    bio: "Notre directeur technique supervise la qualité de toutes nos réalisations et gère les chantiers grands projets à travers le Maroc.",
    image: "/images/projects/Divers__projets_divers_2__001.jpg",
  },
  {
    name: "Direction Commerciale",
    role: "Responsable Commerciale",
    bio: "Notre équipe commerciale accompagne nos clients depuis le premier contact jusqu'à la livraison.",
    image: "/images/projects/Divers__projets_divers_3__001.jpg",
  },
  {
    name: "Équipe Chantier",
    role: "Chefs d'Équipe Certifiés",
    bio: "45 artisans et techniciens hautement qualifiés, formés aux dernières normes de plâtrerie.",
    image: "/images/projects/Divers__projets_divers_4__001.jpg",
  },
];

export const historyTimeline = [
  {
    year: "2008",
    title: "Fondation d'ART PLASTER",
    description: "Mr MABCHOUR MOHAMED fonde ART PLASTER SARL à Salé avec une équipe d'artisans spécialisés.",
  },
  {
    year: "2010",
    title: "Premiers Grands Projets Hôteliers",
    description: "ART PLASTER réalise ses premiers projets hôteliers, établissant sa réputation dans le secteur.",
  },
  {
    year: "2015",
    title: "Développement du Secteur Bancaire",
    description: "Début du partenariat avec les grandes banques marocaines pour leurs agences et sièges sociaux.",
  },
  {
    year: "2018",
    title: "Expansion Nationale",
    description: "ART PLASTER intervient sur tout le territoire marocain, de Laâyoune à Tanger.",
  },
  {
    year: "2021",
    title: "Projets Institutionnels de Prestige",
    description: "Réalisation pour la Fondation Mohamed VI et la Fondation Lalla Salma — CHOP Fès.",
  },
  {
    year: "2023",
    title: "Leader National Confirmé",
    description: "Plus de 300 projets livrés, 45 personnes qualifiées, référence nationale en travaux de plâtre.",
  },
];

export const values = [
  {
    icon: "Star",
    title: "Excellence Artisanale",
    description: "Chaque centimètre carré est traité avec la même rigueur. Notre standard minimum est la perfection.",
  },
  {
    icon: "Shield",
    title: "Intégrité & Fiabilité",
    description: "Devis transparents, délais respectés, engagement tenu. La confiance de nos clients est notre actif.",
  },
  {
    icon: "Users",
    title: "Capital Humain",
    description: "Nos 45 artisans sont notre fierté. Formation continue et conditions de travail exemplaires.",
  },
  {
    icon: "Building2",
    title: "Expertise Sectorielle",
    description: "Finance, hôtellerie, santé, éducation — ART PLASTER maîtrise les exigences de chaque secteur.",
  },
];

export const jobs = [
  {
    id: "1",
    title: "Chef d'Équipe Plâtrerie",
    type: "CDI",
    location: "Salé / National",
    department: "Production",
    description: "Nous recherchons un chef d'équipe expérimenté pour superviser nos chantiers.",
    requirements: [
      "Minimum 5 ans d'expérience en travaux de plâtre",
      "Maîtrise des faux plafonds, cloisons et enduits",
      "Capacité à gérer une équipe de 5 à 15 personnes",
      "Permis B obligatoire",
    ],
    benefits: ["Salaire compétitif", "Formation continue", "Véhicule de service", "Mutuelle"],
  },
  {
    id: "2",
    title: "Technicien Plâtrerie Senior",
    type: "CDI",
    location: "Salé / National",
    department: "Production",
    description: "Rejoignez notre équipe technique pour intervenir sur des chantiers d'envergure nationale.",
    requirements: [
      "Diplôme en bâtiment ou formation équivalente",
      "Maîtrise des techniques de plâtrerie moderne",
      "Expérience dans les projets médicaux ou hôteliers appréciée",
      "Disponibilité pour déplacements",
    ],
    benefits: ["Projets stimulants", "Évolution rapide", "Congés généreux", "Primes de chantier"],
  },
  {
    id: "3",
    title: "Commercial B2B — BTP & Tertiaire",
    type: "CDI",
    location: "Salé / Casablanca / National",
    department: "Commercial",
    description: "Développez notre portefeuille clients dans les secteurs hôtelier, bancaire et médical.",
    requirements: [
      "3 ans minimum en vente B2B dans la construction",
      "Réseau établi dans l'industrie du bâtiment marocaine",
      "Excellentes capacités de négociation",
      "Disponibilité pour déplacements fréquents",
    ],
    benefits: ["Commission attractive", "Voiture de fonction", "Carte essence", "Remboursement frais"],
  },
];

export const perks = [
  { icon: "GraduationCap", title: "Formation Continue", description: "Programmes de formation interne chaque année" },
  { icon: "HeartHandshake", title: "Mutuelle", description: "Couverture santé pour nos collaborateurs" },
  { icon: "TrendingUp", title: "Évolution Rapide", description: "Parcours de carrière clair avec revalorisations annuelles" },
  { icon: "Sun", title: "Congés Généreux", description: "Congés payés annuels selon ancienneté" },
  { icon: "Car", title: "Mobilité", description: "Véhicule ou indemnités kilométriques selon le poste" },
  { icon: "Award", title: "Primes de Performance", description: "Système de bonus lié aux résultats de chantier" },
];
